module.exports = {
  pathPrefix: '',
  siteUrl: 'https://stupefied-johnson-520668.netlify.app',
  siteTitle: 'Gibelli Christophe',
  siteDescription: 'Journal de bord d\'un développeur Front End',
  author: 'Gibelli Christophe',
  postsForArchivePage: 3,
  defaultLanguage: 'fr',
  disqusScript: process.env.DISQUS_SCRIPT,
  pages: {
    home: '/',
    blog: 'blog',
    contact: 'contact',
    resume: 'resume',
    tag: 'tags',
    creation: 'creation',
  },
  social: {
    github: 'https://github.com/ChrisGibe',
    facebook: 'https://www.facebook.com/rolwin.monteiro',
    twitter: 'https://twitter.com/GibelliChris',
    instagram: 'https://www.instagram.com/chris.gibe/',
    rss: '/rss.xml',
  },
  contactFormUrl: process.env.CONTACT_FORM_ENDPOINT || 'https://getform.io/f/eb49b53d-2831-41ae-a929-46af3131b8e6',
  googleAnalyticTrackingId: process.env.GA_TRACKING_ID || '',
  tags: {
    javascript: {
      name: 'javascript',
      description: 'JavaScript est un langage de programmation orienté objet utilisé avec HTML et CSS pour donner des fonctionnalités aux pages Web.',
      color: '#f0da50',
    },
    nodejs: {
      name: 'Node.js',
      description: 'Node.js est un outil pour exécuter JavaScript dans une variété d\'environnements.',
      color: '#90c53f',
    },
    wordpress: {
      name: 'Wordpress',
      description: 'WordPress est un système de gestion de contenu gratuit, libre et open-source. Ce logiciel écrit en PHP repose sur une base de données MySQL',
      color: '#207297',
    },
    typescript: {
      name: 'typescript',
      description: 'TypeScript est un sur-ensemble typé de JavaScript qui se compile en JavaScript simple.',
      color: '#257acc',
    },
    reactjs: {
      name: 'reactjs',
      description: 'React est une bibliothèque JavaScript open source utilisée pour concevoir des interfaces utilisateur.',
      color: '#61dbfa',
    },
    gatsby: {
      name: 'Gatsby.js',
      description: 'Un framework construit sur ReactJS pour générer une application web de page statique.',
      color: '#6f309f',
    },
    html: {
      name: 'HTML',
      description: 'Un langage de balisage qui alimente le Web. Tous les sites Web utilisent HTML pour structurer le contenu.',
      color: '#dd3431',
    },
    css: {
      name: 'css',
      description: 'CSS est utilisé pour styliser l\'élément HTML et donner un aspect très sophistiqué à l\'application Web.',
      color: '#43ace0',
    },
    freelance: {
      name: 'Freelance',
      description: 'Je partage ma nouvelle vide d\'indépendant avec vous',
      color: '#f9c646',
    },
  },
  creations: {
    chalets: {
      name: 'Chalets et Caviar',
      technology: 'Wordpress',
      color: '#43ace0',
      url: 'https://wordpress-409224-1306010.cloudwaysapps.com/',
      img: 'chalets.JPG',
    },
    festival: {
      name: 'Festival des films en plein air',
      technology: 'Bootstrap',
      color: '#257acc',
      url: 'https://projet3oc.netlify.app/',
      img: 'festival.JPG',
    },
    citations: {
      name: 'Générateur de citations',
      technology: 'Javascript',
      color: '#f0da50',
      url: 'https://projet5oc.netlify.app',
      img: 'chalets.JPG',
    },
    jeu: {
      name: 'Jeu de plateau',
      technology: 'Javascript et JQuery',
      color: '#f0da50',
      url: 'https://projet6oc.netlify.app',
      img: 'chalets.JPG',
    },
    localisation: {
      name: 'Application d\'avis de réstaurants',
      technology: 'Javascript',
      color: '#f0da50',
      url: 'https://projet7oc.com/',
      img: 'chalets.JPG',
    },
    ong: {
      name: 'ONG AIESOR',
      technology: 'Wordpress',
      color: '#43ace0',
      url: 'https://wordpress-409224-1287621.cloudwaysapps.com/',
      img: 'chalets.JPG',
    },
  },
};
